### PR TITLE
feat: Render View

### PR DESCRIPTION
**Pull request by rayblair06**
In this PR, you'll find examples of how Dumbo could render views using template engines like Blade, Latte, Twig, or really any template engine, all within the Context service. Let me know your thoughts!

### CODE REVIEW

**Review by notrab — APPROVED** [review]
This is pretty cool @rayblair06. I'd be happy to merge this, really flexible! I do need to learn a bit more about the `use Closure` part, haven't really used that before 😍

**Comment by notrab** [comment]
@rayblair06 do you think it's worth adding something like this?

```php
public function shareWithViews(string $key, $value): void
{
  $this->sharedViewData[$key] = $value;
}

public function view(...$params): ResponseInterface
   {
       // Merge shared data with view-specific data

       $viewData = array_merge($this->sharedViewData, $params[1] ?? []);
       $params[1] = $viewData;

       // ... 
   }
```

**Comment by rayblair06** [comment]
@notrab would this be to share global variables across views?

```
$app->get("/", function ($context) {
    $context->shareWithView('user', [
        'username' => 'Ray'
    ]);
    ...
});

$app->get("/foo", function ($context) {
    // Would have access to user['username'] without having to pass it?
    $context->view('view', []);
});
```

**Comment by notrab** [comment]
> @notrab would this be to share global variables across views?
> 
> 
> 
> ```
> 
> $app->get("/", function ($context) {
> 
>     $context->shareWithView('user', [
> 
>         'username' => 'Ray'
> 
>     ]);
> 
>     ...
> 
> });
> 
> 
> 
> $app->get("/foo", function ($context) {
> 
>     // Would have access to user['username'] without having to pass it?
> 
>     $context->view('view', []);
> 
> });
> 
> ```

I thought anyway @rayblair06 but perhaps it's not the best idea. Let

**Pull request merged**
