### PR TITLE
reorganize the current example into a `simple` folder

### PR DESCRIPTION
**Pull request by josephajibodu**
Updated the examples directory structure to accommodate additional examples. 
Moved the existing example into a `simple` subdirectory under `examples/`

### CODE REVIEW

**Comment by notrab** [comment]
@josephajibodu this looks great! Although, I just merged something to `main` from another PR that causes a conflict.

**Comment by josephajibodu** [comment]
@notrab I will rebase, then make an update

**Comment by notrab** [comment]
@josephajibodu perfect! I created a discord btw https://discord.gg/CYkq2A6G

**Comment by josephajibodu** [comment]
Great, I would join now.

**Pull request merged**
