### PR TITLE
CSRF Protection middleware

### LINKED ISSUE #50: CSRF Protection middleware
When creating the `cookie-auth` example I wanted to use CSRF Protection but thought this would be better as Middleware, similar to how Hono does it https://hono.dev/docs/middleware/builtin/csrf

### PR DESCRIPTION
**Pull request by AymaneIsmail**
I feel that the current implementation of CSRF middleware does not provide sufficient protection against CSRF attacks 😅

This code relies heavily on the `Origin` header: an attacker can easily forge this header, bypassing our protection

After some research, it seems that the best way to implement CSRF protection is to use a token-based verification system with either : 
1. A token stored in a cookie
2. A token that will be stored in the X-CSRF header that will be returned with each request.

What do you think ? 

Closes #50

### CODE REVIEW

**Comment by notrab** [comment]
@AymaneIsmail yeah you're right, a token-based approach is indeed more secure and recommended. Origin header is also not present on some older browsers which is worth remembering.

What do you think about expanding the options so the user has to pass their own getter/setter? I kinda think it's probably more composable than just using the built-in CookieHelper.

Something like this...

```php
<?php

namespace Dumbo\Middleware;

use Closure;
use Dumbo\Context;
use Psr\Http\Message\ResponseInterface;

class CsrfMiddleware
{
    const SAFE_METHODS = ['GET', 'HEAD', 'OPTIONS', 'TRACE'];
    const TOKEN_LENGTH = 32;
    const TOKEN_NAME = 'csrf_token';
    const HEADER_NAME = 'X-CSRF-Token';

    public static function csrf(array $options = []): Closure
    {
        $tokenName = $options['tokenName'] ?? self::TOKEN_NAME;
        $headerName = $options['headerName'] ?? self::HEADER_NAME;
        $useHeader = $options['useHeader'] ?? false;
        $getToken = $options['getToken'] ?? null;
        $setToken = $options['setToken'] ?? null;
        $errorHandler = $options['errorHandler'] ?? null;

        if (!is_callable($getToken) || !is_callable($setToken)) {
            throw new \InvalidArgumentException('getToken and setToken must be callable');
        }

        if ($errorHandler !== null && !is_callable($errorHandler)) {
            throw new \InvalidArgumentException('errorHandler must be callable if provided');
        }

        return function (Context $ctx, callable $next) use ($tokenName, $headerName, $useHeader, $getToken, $setToken, $errorHandler) {
            if (self::isSafeMethod($ctx->req->method())) {
                return self::handleSafeMethod($ctx, $next, $tokenName, $headerName, $useHeader, $getToken, $setToken);
            }

            if (!self::validateToken($ctx, $tokenName, $headerName, $useHeader, $getToken)) {
                return self::handleError($ctx, $errorHandler);
            }

            return $next($ctx);
        };
    }

    private static function isSafeMethod(string $method): bool
    {
        return in_array(strtoupper($method), self::SAFE_METHODS);
    }

    private static function handleSafeMethod(Context $ctx, callable $next, string $tokenName, string $headerName, bool $useHeader, callable $getToken, callable $setToken): mixed
    {
        $token = $getToken($ctx);
        
        if (!$token) {
            $token = self::generateToken();
            $setToken($ctx, $token);
        }

        if ($useHeader) {
            $ctx->header($headerName, $token);
        }

        return $next($ctx);
    }

    private static function validateToken(Context $ctx, string $tokenName, string $headerName, bool $useHeader, callable $getToken): bool
    {
        $storedToken = $getToken($ctx);
        
        if (!$storedToken) {
            return false;
        }

        $receivedToken = $useHeader 
            ? $ctx->req->header($headerName)
            : $ctx->req->body()[$tokenName] ?? null;

        return hash_equals($storedToken, $receivedToken);
    }

    private static function generateToken(): string
    {
        return bin2hex(random_bytes(self::TOKEN_LENGTH / 2));
    }

    private static function handleError(Context $ctx, ?callable $errorHandler): ResponseInterface
    {
        if ($errorHandler) {
            return $errorHandler($ctx);
        }

        // Default error response if no custom handler is provided
        return $ctx->json(['error' => 'Invalid CSRF token'], 403);
    }
}
```

Which then means the user can do:

```php
use Dumbo\Middleware\CsrfMiddleware;
use MyApp\Helpers\MyCookie;

$app->use(CsrfMiddleware::csrf([
    'getToken' => function ($ctx) {
        return MyCookie::get($ctx, 'csrf_token');
    },
    'setToken' => function ($ctx, $token) {
        MyCookie::set($ctx, 'csrf_token', $token, [
            'httpOnly' => true,
            'secure' => true,
            'sameSite' => 'Lax',
        ]);
    },
]));
```

With a custom error response:

```php
$app->use(CsrfMiddleware::csrf([
    'getToken' => function ($ctx) { /* ... */ },
    'setToken' => function ($ctx, $token) { /* ... */ },
    'errorHandler' => function ($ctx) {
        return $ctx->html('<h1>403 Forbidden</h1><p>Invalid CSRF token</p>', 403);
    },
]));
```

Or with session storage:

```php
use Dumbo\Middleware\CsrfMiddleware;

$app->use(CsrfMiddleware::csrf([
    'getToken' => function ($ctx) {
        return $_SESSION['csrf_token'] ?? null;
    },
    'setToken' => function ($ctx, $token) {
        $_SESSION['csrf_token'] = $token;
    },
]));
```

**Comment by notrab** [comment]
One mistake I made above was always using the `json` response. Perhaps we also provide this an option so users can change the behaviour of the error response?

**Comment by notrab** [comment]
@AymaneIsmail This looks really good ⭐ 

I pushed a few fixes for the demo btw.

I was also thinking, what if in the csrf middleware we added the token to the context so you could access the token by doing `$c->get('csrf_token')` in the handlers?

**Comment by notrab** [comment]
@AymaneIsmail I actually get `{"error":"Invalid CSRF token"}` on second attempt of the cookie-auth demo. This could well be the demo I created, not your code 😆

**Comment by notrab** [comment]
@AymaneIsmail are you good if we merge this now? I don't think there is anything outstanding...

**Comment by AymaneIsmail** [comment]
> @AymaneIsmail are you good if we merge this now? I don't think there is anything es, I totally forgot to tell you about the PR, excuse me.

> @AymaneIsmail are you good if we merge this now? I don't think there is anything outstanding...


Yes excuse me, I totally forgot to tell you about the PR 😅

**Pull request merged**
